version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = false

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/kube-tarian/tarian"
  dependencies_vendored = true
 