run:
  timeout: 10m
  concurrency: 4
  skip-files:
  - pkg/nodeagent/ebpf/exec.go

concurrency: 4

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet 
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - dupl
    - stylecheck

linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 400

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0