env:
  - CONTAINER_REGISTRY={{ if index .Env "CONTAINER_REGISTRY" }}{{ .Env.CONTAINER_REGISTRY }}{{ else }}localhost:5000{{ end }}
  - CGO_CFLAGS=-I{{ abs .ModulePath }}/output -Wno-unknown-attributes
builds:
  - id: tarian-server
    main: ./cmd/tarian-server/
    binary: tarian-server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
      - -extldflags "-static"
  - id: tarian-cluster-agent
    main: ./cmd/tarian-cluster-agent/
    binary: tarian-cluster-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
      - -extldflags "-static"
  - id: tarian-node-agent
    main: ./cmd/tarian-node-agent/
    binary: tarian-node-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=netgo
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
      - -extldflags "-static"
  - id: tarian-pod-agent
    main: ./cmd/tarian-pod-agent/
    binary: tarian-pod-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
      - -extldflags "-static"
  - id: tarianctl
    main: ./cmd/tarianctl/
    binary: tarianctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
      - -extldflags "-static"

dockers:
  - ids:
    - tarian-server
    goos: linux
    goarch: amd64
    image_templates:
    - '{{ .Env.CONTAINER_REGISTRY }}/tarian-server:{{ if .IsSnapshot }}latest{{ else }}{{ trimprefix .Tag "v" }}{{ end }}'
    dockerfile: Dockerfile-server
    skip_push: false
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{ .GitURL }}"
  - ids:
    - tarian-cluster-agent
    goos: linux
    goarch: amd64
    image_templates:
    - '{{ .Env.CONTAINER_REGISTRY }}/tarian-cluster-agent:{{ if .IsSnapshot }}latest{{ else }}{{ trimprefix .Tag "v"}}{{ end }}'
    dockerfile: Dockerfile-cluster-agent
    skip_push: false
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{ .GitURL }}"
  - ids:
    - tarian-pod-agent
    goos: linux
    goarch: amd64
    image_templates:
    - '{{ .Env.CONTAINER_REGISTRY }}/tarian-pod-agent:{{ if .IsSnapshot }}latest{{ else }}{{ trimprefix .Tag "v" }}{{ end }}'
    dockerfile: Dockerfile-pod-agent
    skip_push: false
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{ .GitURL }}"
  - ids:
    - tarian-node-agent
    goos: linux
    goarch: amd64
    image_templates:
    - '{{ .Env.CONTAINER_REGISTRY }}/tarian-node-agent:{{ if .IsSnapshot }}latest{{ else }}{{ trimprefix .Tag "v" }}{{ end }}'
    dockerfile: Dockerfile-node-agent
    skip_push: false
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{ .GitURL }}"
  - ids:
    - tarianctl
    goos: linux
    goarch: amd64
    image_templates:
    - '{{ .Env.CONTAINER_REGISTRY }}/tarianctl:{{ if .IsSnapshot }}latest{{ else }}{{ trimprefix .Tag "v" }}{{ end }}'
    dockerfile: Dockerfile-tarianctl
    skip_push: false
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.title={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{ .GitURL }}"
