# FROM cgr.dev/chainguard/static:latest
# FROM cgr.dev/chainguard/static@sha256:2ea44d9bdd177a07e6fba8a60f7d45cb8a7358586a5f740187866566e6df310d
FROM ubuntu

COPY ./tarian-node-agent-loadtest ./

ENTRYPOINT ["./tarian-node-agent-loadtest"]

