# FROM alpine:3.14
FROM alpine@sha256:e7d88de73db3d3fd9b2d63aa7f447a10fd0220b7cbf39803c803f2af9ba256b3

RUN apk --no-cache add ca-certificates
COPY ./tarian-cluster-agent .

ENTRYPOINT ["./tarian-cluster-agent"]

