apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarian-server
spec:
  selector:
    matchLabels:
      app: tarian-server
  replicas: 1
  template:
    metadata:
      labels:
        app: tarian-server
    spec:
      containers:
      - name: tarian-server
        image: "localhost:5000/tarian-server:latest"
        args:
        - "--log-formatter=json"
        - "--log-level=debug"
        - run
        - "--alertmanager-address=http://alertmanager:9093"
        - "--alert-evaluation-interval=3s"
        - "--nats-url=nats:4222"
        ports:
        - containerPort: 50051
          name: grpc
        env:
        - name: DGRAPH_ADDRESS
          value: dgraph-public:9080
---
apiVersion: v1
kind: Service
metadata:
  name: tarian-server
  labels:
    app: tarian-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 50051
    nodePort: 31051
    name: grpc
  selector:
    app: tarian-server
---

