apiVersion: v1
kind: Secret
metadata:
  name: tarian-server
stringData:
  postgresql_password: {{ .Values.server.postgresql.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tarian-server-db-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
stringData:
  postgresql_password: {{ .Values.server.postgresql.password | quote }}