apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tarian-node-agent
spec:
  selector:
    matchLabels:
      app: tarian-node-agent
  template:
    metadata:
      labels:
        app: tarian-node-agent
    spec:
      containers:
      - name: tarian-node-agent
        image: localhost:5000/tarian-node-agent:latest
        args:
        - --log-level=debug
        - --log-formatter=json
        - run
        - --cluster-agent-host=tarian-cluster-agent.tarian-system.svc
        - --cluster-agent-port=80
        - --node-name=$(NODE_NAME)
        - --enable-add-constraint
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: host-proc
          mountPath: /host/proc
        - name: bpf-maps
          mountPath: /sys/fs/bpf
          mountPropagation: Bidirectional
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      serviceAccountName: tarian-node-agent
      volumes:
      - name: host-proc
        hostPath:
          path: /host/proc
      - hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
        name: bpf-maps
