# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# hadoint is a Dockerfile linter written in Haskell
# that helps you build best practice Docker images.
# More details at https://github.com/hadolint/hadolint

name: Dockerfile linting

on:
  pull_request:
    branches:
      - main
    paths:
      - Dockerfile*

permissions:
  contents: read

jobs:
  hadolint-tarian-server:
    name: Run hadolint scanning on tarian-server
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0

      - name: Run hadolint
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183 # @2.1.0
        with:
          dockerfile: ./Dockerfile-server
          format: sarif
          output-file: hadolint-results-server.sarif
          no-fail: true

      - name: Upload hadolint-results-server to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results-server.sarif
          wait-for-processing: true

  hadolint-tarian-cluster-agent:
    name: Run hadolint scanning on tarian-cluster-agent
    runs-on: ubuntu-latest
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0

      - name: Run hadolint
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183 # @2.1.0
        with:
          dockerfile: ./Dockerfile-cluster-agent
          format: sarif
          output-file: hadolint-results-cluster-agent.sarif
          no-fail: true

      - name: Upload hadolint-results-cluster-agent to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results-cluster-agent.sarif
          wait-for-processing: true
